name: deploy react app
on: push
jobs:
  deploy-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: clone-repository
        uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
      - name: install npm packages
        run: npm install
      - name: npm run build
        run: npm run build
      - name: test the application
        run: npm run test
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
