name: deploy react app
on: push
jobs:
  deploy-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: clone-repository
        uses: actions/checkout@v4
      - name: install npm packages
        run: npm install
      - name: npm run build
        run: npm run build
      - name: test the application
        run: npm run test
